#!D:\1\hexstrike-ai\hexstrike-env\Scripts\python3.exe
## -*- coding: utf-8 -*-
##
##  Jonathan Salwan - 2014-05-12 - ROPgadget tool
##
##  http://twitter.com/JonathanSalwan
##  http://shell-storm.org/project/ROPgadget/
##

import ropgadget

ropgadget.main()
